// Country and subdivision names, so a filter reads "United States" rather than "US".
//
// ISO codes are specialist notation. There is no reason a reader would know that NZ is New Zealand,
// and "MD" is genuinely ambiguous — Moldova as a country, Maryland as a US state — so the same two
// letters mean different things depending on which field they are in. Showing names is not a
// convenience, it is correct labelling.
//
// SUBDIVISIONS ARE ONLY MAPPED WHERE THE SOURCE ABBREVIATES THEM. PeeringDB's `state` field is
// freeform: the US, Canada, Australia and Brazil send codes, while India sends "Maharashtra" and
// others send nothing. Anything without a match passes through unchanged rather than being dropped
// or guessed at — a name we cannot expand is still a name someone wrote down.

export const COUNTRY_NAMES = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CD": "DR Congo",
  "CF": "Central African Republic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "Côte d'Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PR": "Puerto Rico",
  "PS": "Palestine",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Türkiye",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

const SUBDIVISIONS = {
  US: {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming"
},
  CA: {
    "AB": "Alberta",
    "BC": "British Columbia",
    "MB": "Manitoba",
    "NB": "New Brunswick",
    "NL": "Newfoundland and Labrador",
    "NS": "Nova Scotia",
    "NT": "Northwest Territories",
    "NU": "Nunavut",
    "ON": "Ontario",
    "PE": "Prince Edward Island",
    "QC": "Quebec",
    "SK": "Saskatchewan",
    "YT": "Yukon"
},
  AU: {
    "ACT": "Australian Capital Territory",
    "NSW": "New South Wales",
    "NT": "Northern Territory",
    "QLD": "Queensland",
    "SA": "South Australia",
    "TAS": "Tasmania",
    "VIC": "Victoria",
    "WA": "Western Australia"
},
  BR: {
    "AC": "Acre",
    "AL": "Alagoas",
    "AM": "Amazonas",
    "AP": "Amapá",
    "BA": "Bahia",
    "CE": "Ceará",
    "DF": "Distrito Federal",
    "ES": "Espírito Santo",
    "GO": "Goiás",
    "MA": "Maranhão",
    "MG": "Minas Gerais",
    "MS": "Mato Grosso do Sul",
    "MT": "Mato Grosso",
    "PA": "Pará",
    "PB": "Paraíba",
    "PE": "Pernambuco",
    "PI": "Piauí",
    "PR": "Paraná",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RO": "Rondônia",
    "RR": "Roraima",
    "RS": "Rio Grande do Sul",
    "SC": "Santa Catarina",
    "SE": "Sergipe",
    "SP": "São Paulo",
    "TO": "Tocantins"
},
};

export function countryName(code) {
  if (!code) return null;
  return COUNTRY_NAMES[code.toUpperCase()] || code;
}

// Spelling variants that mean the same place. PeeringDB and OpenStreetMap both take this field as
// free text from whoever filled the form, so Germany arrived as 42 dropdown entries where it has
// 16 states: "Bavaria" and "Bayern", "Hessen" and "Hesse" and "Hessia", "NRW" and
// "Nordrhein-Westfalen" and "North Rhine-Westphalia", "Baden-Wuerttemberg" and
// "Baden-Württemberg".
//
// Only the countries where the duplication is bad enough to matter. A country listing three
// regions where it should list two is untidy; one listing 42 where it should list 16 makes a
// reader doubt every other number on the page.
//
// Keys are lowercased and stripped of accents before lookup, so "Baden-Württemberg" and
// "baden-wuerttemberg" both land here without needing an entry each.
const ALIASES = {
  DE: {
    "bayern": "Bavaria", "oberbayern": "Bavaria", "oberpfalz": "Bavaria", "mittelfranken": "Bavaria",
    "hessen": "Hesse", "hessia": "Hesse", "darmstadt": "Hesse", "giessen": "Hesse", "gießen": "Hesse",
    "nrw": "North Rhine-Westphalia", "nordrhein-westfalen": "North Rhine-Westphalia",
    "dusseldorf": "North Rhine-Westphalia", "koln": "North Rhine-Westphalia",
    "munster": "North Rhine-Westphalia", "detmold": "North Rhine-Westphalia",
    "baden-wuerttemberg": "Baden-Württemberg", "bw": "Baden-Württemberg",
    "stuttgart": "Baden-Württemberg", "freiburg": "Baden-Württemberg",
    "niedersachsen": "Lower Saxony", "hannover": "Lower Saxony", "weser-ems": "Lower Saxony",
    "sachsen": "Saxony", "leipzig": "Saxony",
    "sachsen-anhalt": "Saxony-Anhalt",
    "thueringen": "Thuringia", "th": "Thuringia",
    "sh": "Schleswig-Holstein", "hh": "Hamburg", "mv": "Mecklenburg-Vorpommern",
    "de": null,
  },
  IN: {
    "maharastra": "Maharashtra", "maharshtra": "Maharashtra", "mh": "Maharashtra",
    "karnataka": "Karnataka", "ka": "Karnataka",
    "tamilnadu": "Tamil Nadu", "tn": "Tamil Nadu",
    "up": "Uttar Pradesh", "wb": "West Bengal", "ap": "Andhra Pradesh",
    "jk": "Jammu and Kashmir", "mp": "Madhya Pradesh", "pb": "Punjab",
  },
  TR: { "istanbul": "İstanbul", "sisli": "İstanbul", "bakirkoy": "İstanbul", "eyup": "İstanbul" },
  ID: {
    "dki jakarta": "Jakarta", "daerah khusus ibukota jakarta": "Jakarta",
    "jakarta selatan": "Jakarta", "jawa barat": "West Java", "jawa tengah": "Central Java",
    "jawa timur": "East Java", "jawatimur": "East Java", "diy": "Yogyakarta",
    "daerah istimewa yogyakarta": "Yogyakarta",
  },
};

// Values that are not a place at all. They came from a form where somebody had to type something.
const NOT_A_PLACE = new Set(["n/a", "na", "nil", "none", "(none)", "not applicable", "other", "-", "."]);

function fold(v) {
  return String(v).trim().toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")   // strip accents: Württemberg -> Wurttemberg
    .replace(/[.,]+$/, "");                             // "Maharashtra," -> "Maharashtra"
}

export function subdivisionName(countryCode, state) {
  if (!state) return null;
  const cc = (countryCode || "").toUpperCase();
  const f = fold(state);
  if (!f || NOT_A_PLACE.has(f)) return null;

  // Aliases first, because they resolve variants the subdivision table would miss. A null value
  // in the alias table means "this is a country code in the state field", which is not a region.
  const alias = ALIASES[cc];
  if (alias && Object.prototype.hasOwnProperty.call(alias, f)) return alias[f];

  const table = SUBDIVISIONS[cc];
  if (table) {
    const hit = table[state.trim().toUpperCase()];
    if (hit) return hit;
    // A full name that already matches one of ours, differing only in case or a trailing comma.
    const byName = Object.values(table).find((v) => fold(v) === f);
    if (byName) return byName;
  }
  // Unrecognised, so returned as written. A name we cannot normalise is still a name somebody
  // typed, and dropping it would hide the record entirely.
  return state.trim().replace(/[.,]+$/, "");
}
